### PR TITLE
Don't load segment for e2e tests

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated test config file
Removed large resolution setting for avoiding segment notifications
Fixed build to use test config for tests

[stage-2]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi @ezequielc please review. Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu curious, disabling segment will also disable intercom chat thing? cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi correct. That's why there's no more issues with the chat thing blocking the Save button with this fix. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome, thanks for fixing that. LG :+1:

**Pull request merged**
