### PR TITLE
Open widget settings

### PR DESCRIPTION
**Pull request by alex-deaconu**
Conditionally show 'cog' for settings (only for widgets)
Factory for opening modal w/ iframe and correct URL
Controller for registering RPC calls

Added `track by` to playlist

[stage-2]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi @ezequielc please review. Thanks.

**Comment by alex-deaconu** [comment]
Build was failing, and stage i18n content was not showing correctly. Rebased this branch off the other 2 PRs to fix. Will rebase again once those are merged. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu LG  :+1:

**Comment by alex-deaconu** [comment]
Thanks!

**Pull request merged**
