### PR TITLE
update common style

### PR DESCRIPTION
**Pull request by ezequielc**
@ghislaineguerin Please review. Thanks

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
:+1: looks good

**Comment by ghislaineguerin** [comment]
@ezequielc but we must update common header here too right? that will require latest common styles

**Comment by ezequielc** [comment]
@ghislaineguerin This was because I had updated CH two days ago and it was breaking the sign up modal.

**Comment by ghislaineguerin** [comment]
@ezequielc thanks!

**Pull request merged**
