### PR TITLE
Fix/layout issues

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu @rodrigopavezi @ezequielc 
Only thing left are sidebar animations that I've lost when I moved all into the same container. I will open a card just for sidebar animations fix.
Also, we need to add that inline styling for the container (width:100%) to happen conditionally on common header when on the presentation view

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ghislaineguerin please squash your commits.

Also, re: conditional class for CH on editor view (width:100%) you can add a card and we can work on that separately.

Otherwise LG to me :+1: . However, please wait to see if @rodrigopavezi @ezequielc have anything to add before merge.

Thanks.

**Comment by ezequielc** [comment]
While improving the code for the editor, I realized that `factory.editing` is only used for simulating the selection of a placeholder in the artboard. So I guess we could replace it with `factory.placeholder` to indicate that we have a selected placeholder. What do you think @alex-deaconu @rodrigopavezi @ghislaineguerin ?
If that is the case, I can make the change in another PR as I am working in a related task.

**Comment by ezequielc** [comment]
Apart from my previous comment, looks all good. :+1: Cheers

**Comment by rodrigopavezi** [comment]
@ghislaineguerin looks good. @ezequielc I think it makes sense to use factory.placeholder. cheers

**Comment by alex-deaconu** [comment]
@ghislaineguerin squashed. I think this is ready for merge. Thanks.

**Pull request merged**
