### PR TITLE
fix publish message

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu please review. Thanks. @rodrigopavezi FYI

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good. I think what we missed is updating the `changedBy` parameter. Also, I'm wondering if the Publish API returns the presentation object. Maybe we should use the data from that object to populate those fields (changedBy, changedDate, revisionStatus)? Thoughts? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I thought about it, but Publish API doesn't return the object. It only returns a "Published" message. We could use Get after publishing, but I think we can just set the values in the way we are doing. What do you think?

**Comment by alex-deaconu** [comment]
@ezequielc sure. Let's leave it as is and we can return to it later to correct. :+1: . Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I updated the changedBy field. Please review. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc nice, thanks for fixing :+1: .

**Pull request merged**
