### PR TITLE
Disable HTML/Design buttons if already selected

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu ng-disabled is not supposed to work in anchor tags. I will have a look later as this build is not staged anymore.

**Comment by alex-deaconu** [comment]
@ezequielc interesting. I didn't know that directive has issues with anchors. I'm staging it now and will double check. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc I updated to use a `<button>` tag instead. Do you think this is a viable solution? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Yes, better than my solution. :+1:

**Pull request merged**
