### PR TITLE
Warning message for unsupported presentation items

### PR DESCRIPTION
**Pull request by ezequielc**
- flag for unsupported items in presentationParser
- watch in workspace controller and show message
- lint

@rodrigopavezi  @alex-deaconu Please review.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good. I'm wondering if the user would find it annoying if this notice pops up every time they opened a presentation (assuming a lot of existing users presentations have them). I'd imagine it would be quite a deterrent to use the new Editor. @ghislaineguerin @ByronDarlison thoughts? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I agree with you. We could also suggest them to migrate/update the presentation to supported Content.
On the other hand, it will be frustrating to open a presentation and not be able to edit the old items. It would look like an issue with the editor. That is why I consider the message to be relevant. Thanks.

**Comment by rodrigopavezi** [comment]
@ezequielc @alex-deaconu what about if the message was in a banner like the one for missing cookies. I think that would be less annoying. cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi good point re. banner. @ezequielc is that doable? And can we make the error more specific, this Presentation contains Gadgets, Video Items, Image Items, HTML Items or Text Items that are not support in this Editor. To modify this Presentation please use the previous version of the Editor by clicking here. And the here should open RVA with that Presentation. Okay? Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison I am not sure about the banner. The one we use today is from common-header. @ghislaineguerin Can we do it in editor?

I will update the text. Thanks

**Comment by ByronDarlison** [comment]
@ezequielc okay. Let's go with it as is and the text changes. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu @rodrigopavezi I changed the text. Please review. Thanks

**Comment by alex-deaconu** [comment]
:+1:

**Pull request merged**
