### PR TITLE
Fix/scrolling list

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@alex-deaconu please review.

**Comment by alex-deaconu** [comment]
@ghislaineguerin reviewed and all looks good. However there's still a slight styling issue with large playlists: http://screencast.com/t/mlUWz8z5aH. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu the issue is fixed now.

**Comment by alex-deaconu** [comment]
@ghislaineguerin looks good, just verified and there's no more scrollbar. Thanks for fixing!

**Pull request merged**
