### PR TITLE
Fix revealing sidebar when selecting placeholder

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc once I have selected a placeholder, I can no longer hide the sidebar by clicking the button. Once I close the specific placeholder via the back button, the sidebar disappears.

I think the logic needs to be revised. 

Thanks.

**Comment by ezequielc** [comment]
Thanks @alex-deaconu , I will have look.

**Comment by ezequielc** [comment]
@alex-deaconu I think now it is working better. Please review again. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc yup, works better. Thanks for fixing :+1: .

**Pull request merged**
