### PR TITLE
Added distribution & timeline to placeholder properties

### PR DESCRIPTION
**Pull request by alex-deaconu**
Switched placeholder-playlist and placeholder-settings names
Update placeholder object on scope rather than use factory object

Implemented integer parsing for variables
Updated parsing to only parse object if present

Fixed jshint error

[stage-2]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi @ezequielc please review. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu looks good. Do we need to change this https://github.com/Rise-Vision/editor-app/blob/feature/placeholder-manage/js/services/svc-presentation-parser.js#L199 as well? cheers

**Comment by ezequielc** [comment]
@alex-deaconu looks good. Cheers.

**Comment by alex-deaconu** [comment]
@rodrigopavezi good catch. However, note the assignment there:
`presentation.hidePointer <== dataObject.hidePointer;`
whereas `parseBooleanProperty` works on the same object. I think it makes sense to leave it as is. Thoughts? Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I see there is a JSON.parse. I am confused because I had to make the checkbox to use string as I was getting string from the editorFactory.presentation. I even set the default like this https://github.com/Rise-Vision/editor-app/blob/master/js/services/svc-presentation-properties-factory.js#L29

I checked now and it is setting boolean on the presentation.hidePointer even though it is like this `"hidePointer": "true"` on the html 

So it looks good I will change the checkbox to use boolean. :+1: 
cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi oh right. I remember seeing that as well. Made sense at the time because the variable was of type String. Currently I'm trying to get all the variables to be the right type (int or boolean rather than String) so we can be consistent. However, I missed updating that particular field. If you can fix that would be great. 

Merging. Thanks!

**Pull request merged**
