### PR TITLE
Visual editor

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu @rodrigopavezi Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good in terms of code. A few comments: 

One thing I would like to see is the Placeholder Name (or some indication thereof) in the Artboard Placeholder. Right now selecting a placeholder is a bit random. 

Another thing to note is that content at the top of the Presentation is not visible/accessible because of the Header (http://screencast.com/t/6Cq6M9zQjqbb). 

@ghislaineguerin thoughts? Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu @ezequielc Ezequiel will add the name and I will style later.

**Comment by ezequielc** [comment]
@alex-deaconu @ghislaineguerin palceholder name added. Please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc LG :+1: . Thanks.

**Pull request merged**
