### PR TITLE
handles Enter in presentation properties

### PR DESCRIPTION
**Pull request by ezequielc**
Fix https://github.com/Rise-Vision/editor-app/issues/117

@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc if I set the name field to be empty, I can still press enter and submit the (invalid) form. I think that's an issue. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Good point. I will add validation. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc also, we currently have a directive for detecting the enter key: https://github.com/Rise-Vision/common-header/blob/master/src/js/dtv-common-header.js#L153. Thanks.

**Comment by ezequielc** [comment]
Thanks @alex-deaconu I will use it. Cheers

**Comment by ezequielc** [comment]
@alex-deaconu I implemented your suggestions. Please review. Thanks

**Comment by ezequielc** [comment]
Thanks @alex-deaconu

**Pull request merged**
